rails3_tr_devise/config/routes.rb
Rails3TrDevise::Application.routes.draw do
  devise_for :users

  resources :customer, :only => [:new, :edit]
  resources :credit_card_info, :only => [:edit]

  match 'customer/confirm' => 'customer#confirm', :as => :confirm_customer
  match 'credit_card_info/confirm' => 'credit_card_info#confirm', :as => :confirm_credit_card_info
  match 'trasactions/:product_id/new' => 'transactions#new', :as => :new_transaction
  match 'transactions/confirm/:product_id' => 'transactions#confirm', :as => :confirm_transaction

  root :to => "welcome#index"
end

rails3_tr_devise/app/models/product.rb
class Product < ActiveRecord::Base
end

rails3_tr_devise/app/models/user.rb
class User < ActiveRecord::Base
  FIELDS = [:first_name, :last_name, :phone, :website, :company, :fax, :addresses, :credit_cards, :custom_fields]

  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessor *FIELDS
  attr_accessible :email, :password, :password_confirmation, :remember_me, :braintree_customer_id

  def has_payment_info?
    !!braintree_customer_id
  end

  def with_braintree_data!
    return self unless has_payment_info?
    braintree_data = Braintree::Customer.find(braintree_customer_id)

    FIELDS.each do |field|
      send(:"#{field}=", braintree_data.send(field))
    end
    self
  end

  def default_credit_card
    return unless has_payment_info?

    credit_cards.find { |cc| cc.default? }
  end
end

rails3_tr_devise/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

rails3_tr_devise/app/controllers/credit_card_info_controller.rb
class CreditCardInfoController < ApplicationController
  before_filter :authenticate_user!

  def edit
    @credit_card = Braintree::CreditCard.find(params[:id])
  end

  def confirm
    @result = Braintree::TransparentRedirect.confirm(request.query_string)

    if @result.success?
      render :action => "confirm"
    else
      @credit_card = Braintree::CreditCard.find(@result.params[:payment_method_token])
      render :action => "edit"
    end
  end
end

rails3_tr_devise/app/controllers/customer_controller.rb
class CustomerController < ApplicationController
  before_filter :authenticate_user!

  def new
    _set_customer_new_tr_data
  end

  def edit
    current_user.with_braintree_data!
    @credit_card = current_user.default_credit_card
    _set_customer_edit_tr_data
  end

  def confirm
    @result = Braintree::TransparentRedirect.confirm(request.query_string)

    if @result.success?
      current_user.braintree_customer_id = @result.customer.id
      current_user.save!
      render :action => "confirm"
    elsif current_user.has_payment_info?
      current_user.with_braintree_data!
      _set_customer_edit_tr_data
      render :action => "edit"
    else
      _set_customer_new_tr_data
      render :action => "new"
    end
  end

  def _set_customer_new_tr_data
    @tr_data = Braintree::TransparentRedirect.
      create_customer_data(:redirect_url => confirm_customer_url)
  end

  def _set_customer_edit_tr_data
    @tr_data = Braintree::TransparentRedirect.
      update_customer_data(:redirect_url => confirm_customer_url,
                           :customer_id => current_user.braintree_customer_id)
  end
end

rails3_tr_devise/app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  before_filter :authenticate_user!

  def new
    if current_user.has_payment_info?
      current_user.with_braintree_data!
      @credit_card = current_user.default_credit_card
      @product = Product.find(params[:product_id])
    else
      redirect_to new_customer_path
    end
  end

  def confirm
    @result = Braintree::TransparentRedirect.confirm(request.query_string)

    if @result.success?
      render :confirm
    else
      @product = Product.find(params[:product_id])
      current_user.with_braintree_data!
      @credit_card = current_user.default_credit_card
      render :new
    end
  end

end

rails3_tr_devise/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index
    redirect_to new_user_session_path unless user_signed_in?

    if current_user && current_user.has_payment_info?
      current_user.with_braintree_data!
      @transactions = Braintree::Transaction.search do |search|
        search.customer_id.is current_user.braintree_customer_id
      end
    end

    @products = Product.all
  end
end

rails3_tr_devise/app/helpers/application_helper.rb
module ApplicationHelper
  class BraintreeFormBuilder < ActionView::Helpers::FormBuilder
    include ActionView::Helpers::AssetTagHelper
    include ActionView::Helpers::TagHelper

    def initialize(object_name, object, template, options, proc)
      super
      @braintree_params = @options[:params]
      @braintree_errors = @options[:errors]
      @braintree_existing = @options[:existing]
    end

    def fields_for(record_name, *args, &block)
      options = args.extract_options!
      options[:builder] = BraintreeFormBuilder
      options[:params] = @braintree_params && @braintree_params[record_name]
      options[:errors] = @braintree_errors && @braintree_errors.for(record_name)
      new_args = args + [options]
      super record_name, *new_args, &block
    end

    def text_field(method, options = {})
      has_errors = @braintree_errors && @braintree_errors.on(method).any?
      field = super(method, options.merge(:value => determine_value(method)))
      result = content_tag("div", field, :class => has_errors ? "fieldWithErrors" : "")
      result.safe_concat validation_errors(method)
      result
    end

    protected

    def determine_value(method)
      if @braintree_params
        @braintree_params[method]
      elsif @braintree_existing

        if @braintree_existing.kind_of?(Braintree::CreditCard)

          case method
          when :number
            method = :masked_number
          when :cvv
            return nil
          end
        end

        @braintree_existing.send(method)
      else
        nil
      end
    end

    def validation_errors(method)
      if @braintree_errors && @braintree_errors.on(method).any?
        @braintree_errors.on(method).map do |error|
          content_tag("div", ERB::Util.h(error.message), {:style => "color: red;"})
        end.join
      else
        ""
      end
    end
  end
end

rails3_tr_devise/app/helpers/credit_card_info_helper.rb
module CreditCardInfoHelper
end

rails3_tr_devise/app/helpers/customers_helper.rb
module CustomersHelper
end

rails3_tr_devise/app/helpers/payment_info_helper.rb
module PaymentInfoHelper
end

rails3_tr_devise/app/helpers/transaction_helper.rb
module TransactionHelper
end

rails3_tr_devise/app/helpers/transactions_helper.rb
module TransactionsHelper
end

rails3_tr_devise/app/helpers/welcome_helper.rb
module WelcomeHelper
end

rails3_tr_devise/app/views/credit_card_info/_form.html.erb
<% if @result %>
  <div style="color:red;" id="total-errors">
    <%= h(@result.errors.size) %> error(s)
  </div>
<% end %>

<%= form_for :credit_card,
      :url => Braintree::TransparentRedirect.url,
      :params => @result && @result.params[:credit_card],
      :builder => ApplicationHelper::BraintreeFormBuilder,
      :existing => @credit_card,
      :errors => @result && @result.errors.for(:credit_card) do |f| %>
  <%= field_set_tag "Credit Card" do %>
    <dl>
      <dt><%= f.label :number, 'Number' %></dt>
      <dd><%= f.text_field :number %></dd>
      <dt><%= f.label :expiration_date, 'Exipration Date (MM/YY)' %></dt>
      <dd><%= f.text_field :expiration_date %></dd>
      <dt><%= f.label :cvv, 'CVV' %></dt>
      <dd><%= f.text_field :cvv %></dd>
    </dl>
  <% end %>
  <%= hidden_field_tag :tr_data, Braintree::TransparentRedirect.
                                   update_credit_card_data(:redirect_url => confirm_credit_card_info_url,
                                                           :payment_method_token => @credit_card.token) %>
  <%= f.submit 'Save Payment Info' %>
<% end %>

rails3_tr_devise/app/views/credit_card_info/confirm.html.erb
<h1>Payment Info Confirmation</h1>
<p>Your payment information was successfully saved.</p>
<dl>
  <dt>Credit Card</dt>
  <dd><%= @result.credit_card.masked_number %></dd>
</dl>

rails3_tr_devise/app/views/credit_card_info/edit.html.erb
<h1>Edit Credit Card <%= @credit_card.masked_number %></h1>
<%= render "form" %>

rails3_tr_devise/app/views/customer/_form.html.erb
<% if @result %>
  <div style="color:red;" id="total-errors">
    <%= h(@result.errors.size) %> error(s)
  </div>
<% end %>

<%= form_for :customer,
      :url => Braintree::TransparentRedirect.url,
      :params => @result && @result.params[:customer],
      :builder => ApplicationHelper::BraintreeFormBuilder,
      :errors => @result && @result.errors.for(:customer) do |f| %>
  <%= field_set_tag "Customer" do %>
    <dl>
      <dt><%= f.label :first_name, 'First Name' %></dt>
      <dd><%= f.text_field :first_name %></dd>
      <dt><%= f.label :last_name, 'Last Name' %></dt>
      <dd><%= f.text_field :last_name %></dd>
      <dt><%= f.label :phone, 'Phone' %></dt>
      <dd><%= f.text_field :phone %></dd>
    </dl>
  <% end %>
  <%= field_set_tag "Credit Card" do %>
    <% f.fields_for :credit_card do |cc| %>
      <dl>
        <dt><%= cc.label :number, 'Number' %></dt>
        <dd><%= cc.text_field :number %></dd>
        <dt><%= cc.label :expiration_date, 'Exipration Date (MM/YY)' %></dt>
        <dd><%= cc.text_field :expiration_date %></dd>
        <dt><%= cc.label :cvv, 'CVV' %></dt>
        <dd><%= cc.text_field :cvv %></dd>
      </dl>
    <% end %>
  <% end %>
  <%= hidden_field_tag :tr_data, @tr_data %>
  <%= f.submit 'Save Payment Info' %>
<% end %>

rails3_tr_devise/app/views/customer/_form_existing.html.erb
<% if @result %>
  <div style="color:red;" id="total-errors">
    <%= h(@result.errors.size) %> error(s)
  </div>
<% end %>

<%= form_for :customer,
      :url => Braintree::TransparentRedirect.url,
      :params => @result && @result.params[:customer],
      :existing => current_user,
      :builder => ApplicationHelper::BraintreeFormBuilder,
      :errors => @result && @result.errors.for(:customer) do |f| %>
  <%= field_set_tag "Customer" do %>
    <dl>
      <dt><%= f.label :first_name, 'First Name' %></dt>
      <dd><%= f.text_field :first_name %></dd>
      <dt><%= f.label :last_name, 'Last Name' %></dt>
      <dd><%= f.text_field :last_name %></dd>
      <dt><%= f.label :phone, 'Phone' %></dt>
      <dd><%= f.text_field :phone %></dd>
    </dl>
  <% end %>
  <% if @credit_card %>
  <ul>
      <li><%= @credit_card.masked_number %> (<%= link_to @credit_card.token, edit_credit_card_info_path(:id => @credit_card.token) %>)</li>
  </ul>
  <% end %>
  <%= hidden_field_tag :tr_data, @tr_data %>
  <%= f.submit 'Save Payment Info' %>
<% end %>

rails3_tr_devise/app/views/customer/confirm.html.erb
<h1>Payment Info Confirmation</h1>
<p>Your payment information was successfully saved.</p>
<dl>
  <dt>First Name</dt>
  <dd><%= @result.customer.first_name %></dd>
  <dt>Last Name</dt>
  <dd><%= @result.customer.last_name %></dd>
  <dt>Phone</dt>
  <dd><%= @result.customer.phone %></dd>
  <dt>Credit Card</dt>
  <% @result.customer.credit_cards.each do |cc| %>
    <dd><%= cc.masked_number %></dd>
  <% end %>
</dl>

rails3_tr_devise/app/views/customer/edit.html.erb
<h1>Edit Payment Info</h1>
<%= render "form_existing" %>

rails3_tr_devise/app/views/customer/new.html.erb
<h1>Add Payment Info</h1>
<%= render "form" %>

rails3_tr_devise/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Rails3TrDevise</title>
  <%= csrf_meta_tag %>
</head>
<body>

<%- flash.each do |name, msg| -%>
  <%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String) %>
<%- end -%>

<p><%= link_to 'Home', root_path %></p>

<% if user_signed_in? -%>
  <div id="user_login_box">
    <%= current_user.email %> |
    <%= link_to 'My info', edit_user_registration_path %> |
    <%= button_to 'Sign out', destroy_user_session_path, :method => 'delete' %>
  </div>
<% end -%>

<%= yield %>

</body>
</html>

rails3_tr_devise/app/views/transactions/_form.html.erb
<% if @result %>
  <div style="color:red;" id="total-errors">
    <%= h(@result.errors.size) %> error(s)
    <%= h(@result.message) %>
  </div>
<% end %>

<%= form_for :transaction,
      :url => Braintree::TransparentRedirect.url,
      :params => @result && @result.params[:transaction],
      :builder => ApplicationHelper::BraintreeFormBuilder,
      :errors => @result && @result.errors.for(:transaction) do |f| %>
  <h2>Customer Information</h2>
  <dl>
    <dt>First Name</dt>
    <dd><%= current_user.first_name %></dd>
    <dt>Last Name</dt>
    <dd><%= current_user.last_name %></dd>
    <dt>Phone</dt>
    <dd><%= current_user.phone %></dd>
  </dl>
  <h2>Credit Card Information</h2>
  <dl>
    <dt>Number</dt>
    <dd><%= @credit_card.masked_number %></dd>
    <dt>Expiration Date</dt>
    <dd><%= @credit_card.expiration_date %></dd>
  </dl>
  <%= hidden_field_tag :tr_data, Braintree::TransparentRedirect.transaction_data(:redirect_url => confirm_transaction_url(:product_id => @product.id),
                                                                                 :transaction => {
                                                                                   :amount => @product.price,
                                                                                   :type => "sale",
                                                                                   :customer_id => current_user.braintree_customer_id
                                                                                  }) %>
  <%= f.submit 'Confirm Purchase', :class => 'buy', :disable_with => 'Please wait...' %>
<% end %>

rails3_tr_devise/app/views/transactions/confirm.html.erb
<h1>Receipt</h1>

<h2>Transaction <%= @result.transaction.id %></h2>

<dl>
  <dt>Amount</dt>
  <dd>$<%= @result.transaction.amount %></dd>
  <dt>Credit Card Charged</dt>
  <dd><%= @result.transaction.credit_card_details.masked_number %></dd>
</dl>

rails3_tr_devise/app/views/transactions/new.html.erb
<h1>Confirm Purchase of <%= @product.name %></h1>
<%= render "form" %>

rails3_tr_devise/app/views/welcome/index.html.erb
<h1>Products</h1>
<table id="products">
  <% @products.each do |p| -%>
    <tr>
      <td><%= p.name %></td>
      <td>$<%= p.price %></td>
      <td><%= link_to "Buy #{p.name}", new_transaction_path(:product_id => p.id) %></td>
    </tr>
  <% end -%>
</table>

<% if @transactions %>
  <h1>Transactions</h1>
  <table id="transactions">
    <%= @transactions.each do |t| -%>
      <tr>
        <td><%= t.id %></td>
        <td><%= t.amount %></td>
        <td><%= t.status.capitalize %></td>
      </tr>
    <% end -%>
  </table>
<% end %>

<dl>
  <% if current_user.has_payment_info? -%>
      <dt>Name</dt>
      <dd><%= current_user.first_name %></dd>
      <dt>Email</dt>
      <dd><%= current_user.email %></dd>
      <dt>Credit Card</dt>
      <dd><%= current_user.credit_cards.first.masked_number%></dd>
      <dt><%= link_to "Edit Your Payment Info", edit_customer_path(current_user.id) %></dt>
  <% else -%>
    <dt><%= link_to "Setup Your Payment Info", new_customer_path  %></dt>
  <% end %>
    <dt>Last Logged In</dt>
    <dd><%= current_user.last_sign_in_at %></dd>
</dl>