rails3_webhooks/config/routes.rb
Rails3Webhook::Application.routes.draw do

  match 'webhooks/process' => 'webhooks#handle', :as => :process_webhook, :via => :post
  match 'webhooks/process' => 'webhooks#verify', :as => :verify_webhook, :via => :get
  match 'webhooks/reset' => 'webhooks#destroy_all', :as => :reset_webhooks, :via => :delete
  resources :webhooks, :only => [:create, :index]

  root :to => 'webhooks#index'

end

rails3_webhooks/app/models/notification_store.rb
class NotificationStore
  def self.add(notification)
    @notifications ||= []
    @notifications << notification
  end

  def self.notifications
    @notifications || []
  end

  def self.clear
    @notifications = []
  end
end

rails3_webhooks/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

rails3_webhooks/app/controllers/webhooks_controller.rb
class WebhooksController < ApplicationController
  def create
    signature, payload = Braintree::WebhookTesting.sample_notification(
      Braintree::WebhookNotification::Kind::SubscriptionWentPastDue,
      rand(10000)
    )
    NotificationStore.add(Braintree::WebhookNotification.parse(signature, payload))
    redirect_to webhooks_path
  end

  def destroy_all
    NotificationStore.clear
    redirect_to webhooks_path
  end

  def handle
    NotificationStore.add(Braintree::WebhookNotification.parse(params[:bt_signature], params[:bt_payload]))
    head :ok
  end

  def index
    @notifications = NotificationStore.notifications
  end

  def verify
    render :text => Braintree::WebhookNotification.verify(params[:bt_challenge])
  end
end

rails3_webhooks/app/helpers/application_helper.rb
module ApplicationHelper
end

rails3_webhooks/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Rails3Webhook</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

rails3_webhooks/app/views/webhooks/index.html.erb
<h1>Notifications</h1>

<%= link_to "create request", webhooks_path, :method => :post %>
<%= link_to "reset", reset_webhooks_path, :method => :delete %>

<table cellspacing="0" cellpadding="0">
  <tr>
    <th>Timestamp</th>
    <th>Kind</th>
    <th>Subscription Id</th>
    <th>Status</th>
    <th>Price</th>
    <th>Balance</th>
    <th>Next Billing Amount</th>
    <th>Billing Period Start Date</th>
    <th>Billing Period End Date</th>
    <th>Current Billing Cycle</th>
    <th>Transaction Ids</th>
  </tr>
  <% @notifications.each do |notification| %>
    <tr>
      <td><%= notification.timestamp %></td>
      <td><%= notification.kind %></td>
      <td><%= notification.subscription.id %></td>
      <td><%= notification.subscription.status %></td>
      <td><%= notification.subscription.price %></td>
      <td><%= notification.subscription.balance %></td>
      <td><%= notification.subscription.next_billing_period_amount %></td>
      <td><%= notification.subscription.billing_period_start_date %></td>
      <td><%= notification.subscription.billing_period_end_date %></td>
      <td><%= notification.subscription.current_billing_cycle %></td>
      <td><%= notification.subscription.transactions.map(&:id).join(", ") %></td>
    </tr>
  <% end %>
</table>